name: CI-CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  continuous-integration-continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy On Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: "username"
          password: "password"
          host: "ip"
          port: "port"
          script: "cd domain.com/public_html/ &&  ./deploy.sh"
